### ISSUE TITLE
String output for localStorage?

### ISSUE THREAD

**Issue by Godefroy** [digital-loukoum/bunker#10]
Hi,

Congrats for this beautiful package!

I'm trying to use bunker with localStorage, but as bunker outputs Uint8Array, I don't know the optimal way to do it.
What would you recommend?

**Comment by julesferreira** [comment]
@Godefroy i found myself needing something similar, and ended up [using a `Buffer` to base64-encode the data](https://github.com/julesferreira/variant-web-storage/blob/2cfc3766218227493afab8d3923215dd235b9ba3/src/index.ts#L121-L126).

_(p.s. regarding your bigint question, i believe `2020` will allow `BigInt(123)` constructors- but `123n` literals aren't available until `esnext`. gl!)_

**Comment by Gin-Quin** [comment]
Hi @Godefroy ,

Indeed the `123n` syntax is not yet well-supported enough so I pushed an update to only use the `BigInt(123)` form. Thanks for the tip @julesferreira 

I actually don't recommend to use Bunker to store data in a browser environment but rather use the native [IndexedDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API). IndexedDB is profiled to achieve exactly this. The API might be cumbersome though so I encourage the use of a library like [idb-keyval](https://github.com/jakearchibald/idb-keyval) which is super-tiny (600 bytes) and add a localStorage-like API layer to IndexedDB.

IndexedDB can store any kind of data including `Uin8Array`s so if really needed you can use it to store bunkered data.
